### ISSUE TITLE
Create a new section explaining personal collections

### ISSUE THREAD

**Issue by sunkup** [bitfireAT/davx5-manual#14]
For https://github.com/bitfireAT/davx5/issues/118

Create a new section under "Accounts and Collections", below [2.7 Refreshing the collection list](https://manual.davx5.com/accounts_collections.html#refreshing-the-collection-list), explaining 
- [ ] personal collections, 
- [ ] the option to show/hide those in the UI 
- [ ] and why they are different from DAV:owner homesets/collections.

**Comment by rfc2822** [comment]
Yes, agree :) We should however keep it as short as possible (and as verbose as required), because it's not really an important function.
